/*from(br)*/CREATE TABLE `_mtable0` (
  `_mcol1gnfr1k` int(11) NOT NULL,
  `_mcolo8og8v` int(11) NOT NULL,
  `_mcolqsbfrx` int(11) NOT NULL,
  `_mcol1arjebt` varchar(16) DEFAULT NULL,
  `_mcolywgquq` char(2) DEFAULT NULL,
  `_mcoll621mh` varchar(16) DEFAULT NULL,
  `_mcoleldw2z` varchar(20) DEFAULT NULL,
  `_mcol1af776` varchar(20) DEFAULT NULL,
  `_mcol13n7bi8` varchar(20) DEFAULT NULL,
  `_mcolp5h03d` char(2) DEFAULT NULL,
  `_mcolbywc95` char(9) DEFAULT NULL,
  `_mcolv9id8t` char(16) DEFAULT NULL,
  `_mcolejrtj` datetime DEFAULT NULL,
  `_mcolwfr8cj` char(2) DEFAULT NULL,
  `_mcolb7fmty` decimal(12,2) DEFAULT NULL,
  `_mcoljq5id4` decimal(4,4) DEFAULT NULL,
  `_mcol5g28ku` decimal(12,2) DEFAULT NULL,
  `_mcol1vhilty` decimal(12,2) DEFAULT NULL,
  `_mcol1phkma8` int(11) DEFAULT NULL,
  `_mcolgs2adr` int(11) DEFAULT NULL,
  `_mcol1fvaavk` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`_mcolqsbfrx`,`_mcolo8og8v`,`_mcol1gnfr1k`) /*T![clustered_index] NONCLUSTERED */,
  KEY `idx_customer` (`_mcolqsbfrx`,`_mcolo8og8v`,`_mcoll621mh`,`_mcol1arjebt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
