/*from(br)*/CREATE TABLE `_mtable7` (
  `_mcoli14qwb` int(11) NOT NULL,
  `_mcol1kehsu1` int(11) NOT NULL,
  `_mcolik6mqj` int(11) DEFAULT NULL,
  `_mcol1yp0b6s` char(24) DEFAULT NULL,
  `_mcol1m6j4dg` char(24) DEFAULT NULL,
  `_mcol11ty5a2` char(24) DEFAULT NULL,
  `_mcols525vy` char(24) DEFAULT NULL,
  `_mcol1cspa2x` char(24) DEFAULT NULL,
  `_mcolwsjli0` char(24) DEFAULT NULL,
  `_mcol6qhytz` char(24) DEFAULT NULL,
  `_mcol7ju2n5` char(24) DEFAULT NULL,
  `_mcol150aakb` char(24) DEFAULT NULL,
  `_mcol13uemo5` char(24) DEFAULT NULL,
  `_mcol1dscb5d` int(11) DEFAULT NULL,
  `_mcol14r50ut` int(11) DEFAULT NULL,
  `_mcolujzctl` int(11) DEFAULT NULL,
  `_mcol1eu33gp` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`_mcol1kehsu1`,`_mcoli14qwb`) /*T![clustered_index] NONCLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
