/*from(br)*/CREATE TABLE `TABLE0` (
  `COL0` int(11) NOT NULL,
  `COL1` int(11) NOT NULL,
  `COL2` int(11) NOT NULL,
  `COL3` varchar(16) DEFAULT NULL,
  `COL4` char(2) DEFAULT NULL,
  `COL5` varchar(16) DEFAULT NULL,
  `COL6` varchar(20) DEFAULT NULL,
  `COL7` varchar(20) DEFAULT NULL,
  `COL8` varchar(20) DEFAULT NULL,
  `COL9` char(2) DEFAULT NULL,
  `COL10` char(9) DEFAULT NULL,
  `COL11` char(16) DEFAULT NULL,
  `COL12` datetime DEFAULT NULL,
  `COL13` char(2) DEFAULT NULL,
  `COL14` decimal(12,2) DEFAULT NULL,
  `COL15` decimal(4,4) DEFAULT NULL,
  `COL16` decimal(12,2) DEFAULT NULL,
  `COL17` decimal(12,2) DEFAULT NULL,
  `COL18` int(11) DEFAULT NULL,
  `COL19` int(11) DEFAULT NULL,
  `COL20` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`COL2`,`COL1`,`COL0`) /*T![clustered_index] NONCLUSTERED */,
  KEY `idx_customer` (`COL2`,`COL1`,`COL5`,`COL3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
