SELECT c_discount, c_last, c_credit, w_tax FROM customer, warehouse WHERE w_id = 42 AND c_w_id = w_id AND c_d_id = 42 AND c_id = 42;
SELECT d_next_o_id, d_tax FROM district WHERE d_id = 42 AND d_w_id = 42 FOR UPDATE;
UPDATE district SET d_next_o_id = 42 + 1 WHERE d_id = 42 AND d_w_id = 42;
INSERT INTO orders (o_id, o_d_id, o_w_id, o_c_id, o_entry_d, o_ol_cnt, o_all_local) VALUES(42, 42, 42, 42, 42, 42, 42);
INSERT INTO new_orders (no_o_id, no_d_id, no_w_id) VALUES (42,42,42);
SELECT i_price, i_name, i_data FROM item WHERE i_id = 42;
SELECT s_quantity, s_data, s_dist_01, s_dist_02, s_dist_03, s_dist_04, s_dist_05, s_dist_06, s_dist_07, s_dist_08, s_dist_09, s_dist_10 FROM stock WHERE s_i_id = 42 AND s_w_id = 42 FOR UPDATE;
UPDATE stock SET s_quantity = 42 WHERE s_i_id = 42 AND s_w_id = 42;
INSERT INTO order_line (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info) VALUES (42, 42, 42, 42, 42, 42, 42, 42, 42);
UPDATE warehouse SET w_ytd = w_ytd + 42 WHERE w_id = 42;
SELECT w_street_1, w_street_2, w_city, w_state, w_zip, w_name FROM warehouse WHERE w_id = 42;
UPDATE district SET d_ytd = d_ytd + 42 WHERE d_w_id = 42 AND d_id = 42;
SELECT d_street_1, d_street_2, d_city, d_state, d_zip, d_name FROM district WHERE d_w_id = 42 AND d_id = 42;
SELECT count(c_id) FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_last = 42;
SELECT c_id FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_last = 42 ORDER BY c_first;
SELECT c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_credit, c_credit_lim, c_discount, c_balance, c_since FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_id = 42 FOR UPDATE;
SELECT c_data FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_id = 42;
UPDATE customer SET c_balance = 42, c_data = 42 WHERE c_w_id = 42 AND c_d_id = 42 AND c_id = 42;
UPDATE customer SET c_balance = 42 WHERE c_w_id = 42 AND c_d_id = 42 AND c_id = 42;
INSERT INTO history(h_c_d_id, h_c_w_id, h_c_id, h_d_id, h_w_id, h_date, h_amount, h_data) VALUES(42, 42, 42, 42, 42, 42, 42, 42);
SELECT count(c_id) FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_last = 42;
SELECT c_balance, c_first, c_middle, c_last FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_last = 42 ORDER BY c_first;
SELECT c_balance, c_first, c_middle, c_last FROM customer WHERE c_w_id = 42 AND c_d_id = 42 AND c_id = 42;
SELECT o_id, o_entry_d, COALESCE(o_carrier_id,0) FROM orders WHERE o_w_id = 42 AND o_d_id = 42 AND o_c_id = 42 AND o_id = (SELECT MAX(o_id) FROM orders WHERE o_w_id = 42 AND o_d_id = 42 AND o_c_id = 42);
SELECT ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_delivery_d FROM order_line WHERE ol_w_id = 42 AND ol_d_id = 42 AND ol_o_id = 42;
SELECT COALESCE(MIN(no_o_id),0) FROM new_orders WHERE no_d_id = 42 AND no_w_id = 42;
DELETE FROM new_orders WHERE no_o_id = 42 AND no_d_id = 42 AND no_w_id = 42;
SELECT o_c_id FROM orders WHERE o_id = 42 AND o_d_id = 42 AND o_w_id = 42;
UPDATE orders SET o_carrier_id = 42 WHERE o_id = 42 AND o_d_id = 42 AND o_w_id = 42;
UPDATE order_line SET ol_delivery_d = 42 WHERE ol_o_id = 42 AND ol_d_id = 42 AND ol_w_id = 42;
SELECT SUM(ol_amount) FROM order_line WHERE ol_o_id = 42 AND ol_d_id = 42 AND ol_w_id = 42;
UPDATE customer SET c_balance = c_balance + 42 , c_delivery_cnt = c_delivery_cnt + 1 WHERE c_id = 42 AND c_d_id = 42 AND c_w_id = 42;
SELECT d_next_o_id FROM district WHERE d_id = 42 AND d_w_id = 42;
SELECT DISTINCT ol_i_id FROM order_line WHERE ol_w_id = 42 AND ol_d_id = 42 AND ol_o_id < 42 AND ol_o_id >= (42 - 20);
SELECT count(*) FROM stock WHERE s_w_id = 42 AND s_i_id = 42 AND s_quantity < 42;
